spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_project?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    username: root
    password: hhants8092
